services:
  jupyter:
    image: thisthiago/jupyter:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    networks:
      - soccer-analytics-net
    env_file:
      - env_files/.env
    depends_on:
      - minio
    volumes:
      - ./notebooks:/home/jovyan/work

  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - soccer-analytics-net
    env_file:
      - env_files/.env
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

networks:
  soccer-analytics-net:
    name: soccer-analytics-net